imdb517/Models/editMovies.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace imdb517.Models
{
    public class editMovies
    {

        public int Id { get; set; }
        public string MoviesName { get; set; }
        public string YearOfRelease { get; set; }
        public string Plot { get; set; }
        public int producerid { get; set; }
        public int Actorid { get; set; }

        public virtual updatedActors updatedActors { get; set; }
        public virtual Producers Producers { get; set; }
    }
}

imdb517/Controllers/imdbController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using imdb517.Models;

namespace imdb517.Controllers
{
    public class imdbController : Controller
    {
        imdbfinalEntities db = new imdbfinalEntities();
        // GET: idmb
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ViewAllMovies()
        {
            try
            {
                List<viewAllMovies_Result> viewAllMovies_Results = db.viewAllMovies().ToList();
                List<newMovieList> newMovieLists = new List<newMovieList>();




                foreach (var x in viewAllMovies_Results)
                {

                    newMovieList newMovieList = new newMovieList();

                    if (newMovieLists.Where(p => p.movieid == x.movieid).Count() == 0)
                    {
                        newMovieList.movieid = x.movieid;
                        newMovieList.id = x.id;

                        newMovieList.Actor1 = viewAllMovies_Results.Where(a => a.movieid == x.movieid).Select(b => b.Actor1).ToList();
                        string actors = string.Join<string>(",", newMovieList.Actor1);
                        viewAllMovies_Results.Where(w => w.movieid == x.movieid).ToList().ForEach(s => s.Actor1 = actors);

                        newMovieLists.Add(newMovieList);
                    }




                }



                viewAllMovies_Results = viewAllMovies_Results.GroupBy(t => t.movieid).Select(g => g.First()).ToList();




                return View(viewAllMovies_Results);
            }
            catch (Exception)
            {

                throw;
            }
            
        }


        public ActionResult ViewAllProducers()
        {
            try
            {
                List<viewAllProducers_Result> viewAllProducers_Results = db.viewAllProducers().ToList();
                db.SaveChanges();
                return View(viewAllProducers_Results);
            }
            catch (Exception)
            {

                throw;
            }
            
        }

        public ActionResult ViewAllActors()
        {
            try
            {
                List<viewAllActors_Result> viewAllProducers_Results = db.viewAllActors().ToList();
                db.SaveChanges();
                return View(viewAllProducers_Results);
            }
            catch (Exception)
            {

                throw;
            }
           
        }

        public ActionResult ViewMovie(int id)
        {
            try
            {
                List<moviedetails_Result> moviedetails_Results = db.moviedetails(id).ToList();
                return View(moviedetails_Results);

            }
            catch (Exception)
            {

                throw;
            }
          
        }

        public ActionResult ViewProducerMovies(int id)
        {
            try
            {
                List<producerMovies_Result> producerMovies_Results = db.producerMovies(id).ToList();
                db.SaveChanges();
                return View(producerMovies_Results);
            }
            catch (Exception)
            {

                throw;
            }
           
        }

        public ActionResult ViewActorMovies(int id)
        {
            try
            {
                List<actorMovies_Result> actorMovies = db.actorMovies(id).ToList();
                db.SaveChanges();
                return View(actorMovies);
            }
            catch (Exception)
            {

                throw;
            }
           
        }

        public ActionResult AllMoviesByProducers(string id)
        {
            try
            {
                List<viewMoviebyProducer_Result> producer_Results = db.viewMoviebyProducer(id).ToList();
                TempData["ProdName"] = id;
                return View(producer_Results);
            }
            catch (Exception)
            {

                throw;
            }
          
        }

        public ActionResult AllMoviesByActor(string id)
        {
            try
            {
                List<viewMoviebyActor_Result> producer_Results = db.viewMoviebyActor(id).ToList();
                TempData["ActorName"] = id;
                return View(producer_Results);
            }
            catch (Exception)
            {

                throw;
            }
           
        }


        public ActionResult AddMovies()
        {
            try
            {
                multi movies = new multi();


                ViewBag.producerid = new SelectList(db.Producers.OrderBy(m => m.ProducersName), "Id", "ProducersName");
                ViewBag.Actorid0 = new SelectList(db.updatedActors.OrderBy(m => m.Actor1), "Id", "Actor1");

                return View(movies);
            }
            catch (Exception)
            {

                throw;
            }
            
        }

        [HttpPost]
        public ActionResult AddMovies(multi movies, FormCollection formCollection)
        {
            try
            {
                string newProducerCheck = formCollection["ProducersName"].Trim();
                string newActorCheck = formCollection["Actor1"].Trim();
                string actor = formCollection["Actorid0"];
                List<int> allactors = actor.Split(',').Select(int.Parse).ToList();


                if (newProducerCheck != null && newProducerCheck != "")
                {
                    movies.producerid = ViewBag.producerid = new SelectList(db.Producers, "Id", "ProducersName").Count();
                }
                if (newActorCheck != null && newActorCheck != "")
                {
                    movies.Actorid = ViewBag.Actorid = new SelectList(db.updatedActors, "Id", "Actor1").Count();
                }

                if (ModelState.ContainsKey("{producerid}"))
                    ModelState["{producerid}"].Errors.Clear();

                if (ModelState.IsValid)
                {

                    int res = db.AddMovies(movies.MoviesName, movies.YearOfRelease, movies.Plot, movies.producerid, movies.image);
                    this.db.SaveChanges();
                    var movieid = db.Movies.SqlQuery("select  * from movies where MoviesName= " + "'" + movies.MoviesName + "'").FirstOrDefault();

                    foreach (var act in allactors)
                    {
                        db.addactorandmovie(movieid.Id, act);
                        this.db.SaveChanges();
                    }
                    TempData["Message"] = movies.MoviesName + "   Movie Added Successfully!";


                }




                ViewBag.producerid = new SelectList(db.Producers, "Id", "ProducersName", movies.producerid);
                ViewBag.Actorid = new SelectList(db.updatedActors, "Id", "Actor1", movies.Actorid);
                return RedirectToAction("ViewAllMovies");
            }
            catch (Exception)
            {

                throw;
            }
           
        }

        public ActionResult addwithprod()
        {
            
            return View();
        }
        [HttpPost]
        public ContentResult addwithprod(multi movies,FormCollection formCollection)
        {

            try
            {
                string ProducerName = formCollection["ProducersName"];
                string Sex = gender(formCollection["Sex"]);
                string DOB = formCollection["DOB"];
                string BIO = formCollection["Bio"];

                if (ProducerName != "" && Sex != "" && BIO != "")
                {
                    db.addProducers(ProducerName, Sex, DOB, BIO);
                    ViewBag.producerid = new SelectList(db.Producers, "Id", "ProducersName");
                    return Content(ProducerName);
                }
                else
                {
                    return Content("Something went wrong");
                }
            }
            catch (Exception)
            {

                throw;
            }

           
            
                
            
          
            
           
        }

        public ActionResult addwithactor()
        {

            return View();
        }
        [HttpPost]
        public ContentResult addwithactor(multi movies, FormCollection formCollection)
        {
            try
            {
                string ActorName = formCollection["Actor1"].Trim();
                string Sex = gender(formCollection["Actor1Sex"]).Trim();
                string DOB = formCollection["Actor1DOB"];
                string BIO = formCollection["Actor1Bio"].Trim();

                if (ActorName != "" && Sex != "" && BIO != "")
                {
                    db.addActors(ActorName, Sex, DOB, BIO);

                    return Content(ActorName);
                }
                else
                {
                    return Content("Something went wrong");
                }
            }
            catch (Exception)
            {

                throw;
            }
           


           
        }
        public ActionResult EditMovies(int id)
        {
            try
            {
                Producers producers = new Producers();


                prefilledEdit_Result prefilledEdit_Result = new prefilledEdit_Result();
                prefilledEdit_Result = db.prefilledEdit(id).FirstOrDefault();
                ViewBag.totalActor = db.totalActors(id).FirstOrDefault();

                TempData["editMovie"] = prefilledEdit_Result.MoviesName;


                ViewBag.producerid = new SelectList(db.Producers.OrderBy(m => m.ProducersName), "Id", "ProducersName");
                ViewBag.Actorid1 = new SelectList(db.updatedActors.OrderBy(m => m.Actor1), "Id", "Actor1");

imdb517/Views/imdb/AllMoviesByActor.cshtml
@model IEnumerable<imdb517.viewMoviebyActor_Result>

<h3>@TempData["ActorName"]</h3>
<table class="table table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MoviesName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.YearOfRelease)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.plot)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProducersName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MoviesName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.YearOfRelease)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.plot)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProducersName)
        </td>
       
    </tr>
}

</table>

imdb517/Views/imdb/AllMoviesByProducers.cshtml
@model IEnumerable<imdb517.viewMoviebyProducer_Result>

<table class="table table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MoviesName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.YearOfRelease)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.plot)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Actor1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProducersName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MoviesName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.YearOfRelease)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.plot)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Actor1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProducersName)
        </td>
      
    </tr>
}

</table>

imdb517/Views/imdb/Delete.cshtml
@model imdb517.prefilledEdit_Result

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}
<head>

    <style>
        .alert {
            display: none;
        }
    </style>
</head>
<div>







    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()


        <div class="alert alert-success">
            <strong> @Model.MoviesName</strong>  has been Deleted successfully.
        </div>

        <h3>Are you sure you want to delete <strong> @Model.MoviesName</strong> ?</h3>
        <div class="container">
            <div class="row">
                <div class="col-md-4">

                    <img class="center-block" src=@Model.imageUrl>

                    <hr />
                    <dl class="dl-horizontal">



                        <dd>
                            @Html.DisplayFor(model => model.Actorid)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.MoviesName)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.MoviesName)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.YearOfRelease)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.YearOfRelease)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Plot)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Plot)
                        </dd>


                        <dd>
                            <input style="margin:5px" type="submit"  id="delete"value="Delete" class="btn btn-danger" />
                        </dd>





                    </dl>
                </div>


            </div>
        </div>

        <script type="text/javascript">
            $(document).ready(function () {
                $('#delete').click(function () {
                    $('.alert').show();

                })
            });
        </script>

    }
</div>

imdb517/Views/imdb/Index.cshtml
<tr>
    <td> Populating With Database and EF </td>
    <td>
        @Html.DropDownList("MySkills", (IEnumerable
       <SelectListItem>)ViewData["DBMySkills"])
    </td>
</tr> 

imdb517/Views/imdb/ViewActorMovies.cshtml
@model IEnumerable<imdb517.actorMovies_Result>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MoviesName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.YearOfRelease)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.plot)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.ProducersName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MoviesName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.YearOfRelease)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.plot)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProducersName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
            @Html.ActionLink("Details", "Details", new { id = item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.id })
        </td>
    </tr>
}

</table>

imdb517/Views/imdb/ViewAllActors.cshtml
@model IEnumerable<imdb517.viewAllActors_Result>

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@


<h3 style="text-align:center">All Actors</h3><span>

    <input type="button" style="margin-bottom:2px" class="btn btn-primary pull-right" value="Add Actor" onclick="location.href='@Url.Action("addActors", "imdb")'" />
    
</span>
<table class="table table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Actor1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sex)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DOB)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Bio)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Actor1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sex)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DOB)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bio)
            </td>
            
        </tr>
    }

</table>

imdb517/Views/imdb/ViewAllMovies.cshtml
@model IEnumerable<imdb517.viewAllMovies_Result>

<h3 style="color:#286090;text-align">@TempData["Message"]</h3>
<h3 style="text-align:center ; margin:25px">All Movies</h3>
<table class="table table-bordered">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.MoviesName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.YearOfRelease)
        </th>
     
        <th>
            @Html.DisplayNameFor(model => model.Actor1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProducersName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.MoviesName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.YearOfRelease)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.Actor1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProducersName)
            </td>
            <td>
                @Html.ActionLink("Details", "ViewMovie", new { id = item.movieid }, new { @class = "btn btn-primary" }) |
                @Html.ActionLink("Edit", "EditMovies", new { id = item.movieid }, new { @class = "btn btn-info" }) |

                @Html.ActionLink("Delete", "Delete", new { id = item.movieid }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }

</table>

imdb517/Views/imdb/ViewAllProducers.cshtml
@model IEnumerable<imdb517.viewAllProducers_Result>

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@

<h3 style="text-align:center">All Producers</h3> <span> 
    <input type="button" class="btn btn-primary pull-right" value="Add Producer" onclick="location.href='@Url.Action("addProcuders", "imdb")'" />
    </span>




<table class="table table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProducersName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sex)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DOB)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Bio)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProducersName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sex)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DOB)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bio)
            </td>
         
        </tr>
    }

</table>

imdb517/Views/imdb/ViewMovie.cshtml
@model IEnumerable<imdb517.moviedetails_Result>


<head>
    <style>
        img {
            float: left;
        }
    </style>
</head>


@foreach (var item in Model)
{


    <div class="container">
        <div class="row">
            <div class="col">
                <a href="@Url.Action("ViewMovie", "imdb", new { id = item.id })">
                    <img style="width:25%;height:40%;margin-left:15px;margin-top: 57px" class="img-responsive center-block" src=@item.imageUrl>
                </a>
            </div>
            <div class="col-lg-offset-7 " >
                <div style="float:left;margin-top:100px">
                    <h2 style="text-align:center;text-transform:uppercase"> <strong> @Html.DisplayFor(modelItem => item.MoviesName)</strong></h2>

                    <ul>




                        <li>
                            <label>Year of Release : </label>
                            @Html.DisplayFor(modelItem => item.YearOfRelease)

                        </li>
                        <li>
                            <label>Producer : </label>
                            <a href="@Url.Action("AllMoviesByProducers", "imdb", new { id = item.ProducersName })">@Html.DisplayFor(modelItem => item.ProducersName)</a>
                            
                        </li>
                        <li>
                            <label>Actors : </label>
                            <a href="@Url.Action("AllMoviesByActor", "imdb", new { id = item.Actor1 })">@Html.DisplayFor(modelItem => item.Actor1)</a>
                            
                        </li>
                        <li>
                            <label>Plot  : </label>
                            @Html.DisplayFor(modelItem => item.plot)
                        </li>

                        <li>
                            @Html.ActionLink("Edit", "EditMovies", new { id = item.movieid }, new { @class = "btn btn-info" }) |

                            @Html.ActionLink("Delete", "Delete", new { id = item.movieid }, new { @class = "btn btn-danger" })
                        </li>
                    </ul>
                </div>
                
               
            </div>
            
        </div>
    </div>


   



    



}

imdb517/Views/imdb/ViewProducerMovies.cshtml
@model IEnumerable<imdb517.producerMovies_Result>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MoviesName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.YearOfRelease)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Plot)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MoviesName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.YearOfRelease)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Plot)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>

imdb517/Views/imdb/addActors.cshtml
@model imdb517.updatedActors

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

@using (Html.BeginForm())
{
<head>
   
    <style>
        .alert {
            display: none;
        }
    </style>
</head>
    @Html.AntiForgeryToken()

    <div class="form-horizontal needs-validation">
        <h2 style="text-align:center">Add Actor</h2>
        <hr />


        <div class="container py-5">


            <div class="alert alert-success">
                <strong>Success!</strong> Actor has been added successfully.
            </div>


        </div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Actor1, htmlAttributes: new { @class = "control-label col-md-2 required" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Actor1, new { htmlAttributes = new { @class = "form-control", } })
                @Html.ValidationMessageFor(model => model.Actor1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sex, htmlAttributes: new { @class = "control-label col-md-2 required" })
            <div class="col-md-10">
                @Html.DropDownList("Sex", new List<SelectListItem>
          {
           new SelectListItem{ Text="Male", Value = "1" },
           new SelectListItem{ Text="Female", Value = "2" },
           new SelectListItem{ Text="Others", Value = "3" } }, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Sex, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2 required" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bio, htmlAttributes: new { @class = "control-label col-md-2 required" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" disabled value="Create" id="producersubmit" class="btn btn-primary" />
            </div>
        </div>
    </div>


    <script type="text/javascript">
        $(document).ready(function () {
            $('#producersubmit').click(function () {
                $('.alert').show();

            })
        });

        $('#Actor1, #Sex, #DOB, #Bio').bind('keyup', function () {
            if (allFilled()) $('#producersubmit').removeAttr('disabled');
        });

        function allFilled() {
            var filled = true;
            $('body input').each(function () {
                if ($(this).val() == '') filled = false;
            });
            return filled;
        }
    </script>
}

imdb517/Views/imdb/addProcuders.cshtml
@model imdb517.Producers

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}
@using (Html.BeginForm())
{
<head>


   
   
</head>
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h2 style="text-align:center">Add Producer</h2>
    <hr />



    <div class="container py-5">
        
        
        <div class="alert alert-success">
            <strong>Success!</strong> Producer has been added successfully.
        </div>
        
       
    </div>





    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.ProducersName, htmlAttributes: new { @class = "control-label col-md-2 required" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ProducersName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ProducersName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Sex, htmlAttributes: new { @class = "control-label col-md-2 required " })
        <div class="col-md-10">
            @Html.DropDownList("Sex", new List<SelectListItem>
       {
        new SelectListItem{ Text="Male", Value = "1" },
        new SelectListItem{ Text="Female", Value = "2" },
        new SelectListItem{ Text="Others", Value = "3" } }, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Sex, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2 required" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control", type = "date" } })
            @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Bio, htmlAttributes: new { @class = "control-label col-md-2 required" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Bio, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Bio, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" id="producersubmit" disabled value="Create" class="btn btn-primary" />
        </div>
    </div>
</div>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#producersubmit').click(function () {
                $('.alert').show();
                
            })
        });

        //$(document).ready(function () {
        //    $("#producersubmit").prop('disabled', true);
        //    $("#Bio").keyup(function () {
        //        if ($(this).val() != '') {
        //            $("#producersubmit").prop('disabled', false);
        //        }
        //    });
        //});



        $('#ProducersName, #Sex, #DOB, #Bio').bind('keyup', function () {
            if (allFilled()) $('#producersubmit').removeAttr('disabled');
        });

        function allFilled() {
            var filled = true;
            $('body input').each(function () {
                if ($(this).val() == '') filled = false;
            });
            return filled;
        }
    </script>
}